version: '3.7'
services:
  streamsinkclient:
    container_name: streamsink-client
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${VUE_APP_APIURL}
        - APP_BASE=${VUE_APP_BASE}
        - APP_NAME=${VUE_APP_NAME}
        - APP_FILEURL=${VUE_APP_FILEURL}
        - APP_SOCKETURL=${VUE_APP_SOCKETURL}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${FILES}:/recordings
    ports:
      - '80:80'
